export const styles = {
    page: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        minHeight: "100vh",
        background: "#f5f5f5",
        fontFamily: "'Segoe UI', sans-serif",
    },
    card: {
        background: "#ffffff",
        borderRadius: "16px",
        width: "300px",
        overflow: "hidden",
        boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
        cursor: "pointer",
    },
    imgWrap: {
        overflow: "hidden",
        height: "200px",
        background: "#f0f4ff",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    img: {
        width: "130px",
        height: "130px",
    },
    body: {
        padding: "1.25rem",
    },
    badge: {
        display: "inline-block",
        fontSize: "11px",
        padding: "3px 10px",
        borderRadius: "8px",
        background: "#e6f0ff",
        color: "#2563eb",
        marginBottom: "8px",
    },
    name: {
        fontSize: "18px",
        fontWeight: "600",
        color: "#111",
        marginBottom: "6px",
    },
    stars: {
        display: "flex",
        alignItems: "center",
        gap: "2px",
        marginBottom: "8px",
    },
    starCount: {
        fontSize: "12px",
        color: "#888",
        marginLeft: "4px",
    },
    desc: {
        fontSize: "13px",
        color: "#666",
        lineHeight: "1.6",
        marginBottom: "1rem",
    },
    priceRow: {
        display: "flex",
        alignItems: "baseline",
        gap: "8px",
        marginBottom: "1rem",
    },
    price: {
        fontSize: "22px",
        fontWeight: "700",
        color: "#111",
    },
    priceOld: {
        fontSize: "14px",
        color: "#aaa",
        textDecoration: "line-through",
    },
    actions: {
        display: "flex",
        gap: "8px",
    },
    btnBuy: {
        flex: 1,
        padding: "10px 0",
        background: "#111",
        color: "#fff",
        border: "none",
        borderRadius: "10px",
        fontSize: "14px",
        fontWeight: "500",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "6px",
        outline: "none",
    },
    btnBuyAdded: {
        background: "#0F6E56",
    },
    btnLike: {
        width: "44px",
        height: "44px",
        border: "1px solid #e5e7eb",
        borderRadius: "10px",
        background: "#fff",
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        outline: "none",
        flexShrink: 0,
    },
};
